CREATE TABLE company (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug VARCHAR(100) NOT NULL,
  name_ko VARCHAR(100) NOT NULL,
  name_en VARCHAR(100) NOT NULL,
  status VARCHAR(30) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_company_slug UNIQUE (slug)
);

CREATE INDEX idx_company_status_name_ko ON company (status, name_ko);

CREATE TABLE source_blog (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  name VARCHAR(150) NOT NULL,
  homepage_url VARCHAR(500) NOT NULL,
  feed_url VARCHAR(500),
  source_type VARCHAR(30) NOT NULL,
  status VARCHAR(30) NOT NULL,
  review_reason TEXT,
  last_collected_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_source_blog_company FOREIGN KEY (company_id) REFERENCES company (id),
  CONSTRAINT uk_source_blog_feed_url UNIQUE (feed_url)
);

CREATE INDEX idx_source_blog_company_id ON source_blog (company_id);
CREATE INDEX idx_source_blog_status ON source_blog (status);

CREATE TABLE job_category (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(50) NOT NULL,
  label_ko VARCHAR(100) NOT NULL,
  display_order INTEGER NOT NULL,
  active BOOLEAN NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_job_category_code UNIQUE (code)
);

CREATE TABLE topic_tag (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug VARCHAR(100) NOT NULL,
  label VARCHAR(100) NOT NULL,
  normalized_label VARCHAR(100) NOT NULL,
  active BOOLEAN NOT NULL,
  merged_to_tag_id BIGINT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_topic_tag_merged_to_tag FOREIGN KEY (merged_to_tag_id) REFERENCES topic_tag (id),
  CONSTRAINT uk_topic_tag_slug UNIQUE (slug)
);

CREATE TABLE archived_post (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_blog_id BIGINT NOT NULL,
  company_id BIGINT NOT NULL,
  slug VARCHAR(180) NOT NULL,
  title VARCHAR(500) NOT NULL,
  origin_url VARCHAR(1000) NOT NULL,
  canonical_url VARCHAR(1000) NOT NULL,
  canonical_fingerprint VARCHAR(128) NOT NULL,
  published_at TIMESTAMP WITH TIME ZONE NOT NULL,
  collected_at TIMESTAMP WITH TIME ZONE NOT NULL,
  processing_state VARCHAR(30) NOT NULL,
  visibility_state VARCHAR(30) NOT NULL,
  review_reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_archived_post_source_blog FOREIGN KEY (source_blog_id) REFERENCES source_blog (id),
  CONSTRAINT fk_archived_post_company FOREIGN KEY (company_id) REFERENCES company (id),
  CONSTRAINT uk_archived_post_slug UNIQUE (slug),
  CONSTRAINT uk_archived_post_canonical_fingerprint UNIQUE (canonical_fingerprint)
);

CREATE INDEX idx_archived_post_company_published ON archived_post (company_id, published_at);
CREATE INDEX idx_archived_post_source_blog_id ON archived_post (source_blog_id);
CREATE INDEX idx_archived_post_visibility_published ON archived_post (visibility_state, published_at, id);
CREATE INDEX idx_archived_post_processing_state ON archived_post (processing_state);

CREATE TABLE archived_post_job_category (
  archived_post_id BIGINT NOT NULL,
  job_category_id BIGINT NOT NULL,
  CONSTRAINT fk_archived_post_job_category_post FOREIGN KEY (archived_post_id) REFERENCES archived_post (id),
  CONSTRAINT fk_archived_post_job_category_job FOREIGN KEY (job_category_id) REFERENCES job_category (id),
  CONSTRAINT uk_archived_post_job_category UNIQUE (archived_post_id, job_category_id)
);

CREATE INDEX idx_archived_post_job_category_job ON archived_post_job_category (job_category_id);

CREATE TABLE archived_post_topic_tag (
  archived_post_id BIGINT NOT NULL,
  topic_tag_id BIGINT NOT NULL,
  CONSTRAINT fk_archived_post_topic_tag_post FOREIGN KEY (archived_post_id) REFERENCES archived_post (id),
  CONSTRAINT fk_archived_post_topic_tag_tag FOREIGN KEY (topic_tag_id) REFERENCES topic_tag (id),
  CONSTRAINT uk_archived_post_topic_tag UNIQUE (archived_post_id, topic_tag_id)
);

CREATE INDEX idx_archived_post_topic_tag_tag ON archived_post_topic_tag (topic_tag_id);

CREATE TABLE post_source_occurrence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  archived_post_id BIGINT NOT NULL,
  source_blog_id BIGINT NOT NULL,
  origin_url VARCHAR(1000) NOT NULL,
  published_at TIMESTAMP WITH TIME ZONE NOT NULL,
  duplicate_type VARCHAR(30) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_post_source_occurrence_post FOREIGN KEY (archived_post_id) REFERENCES archived_post (id),
  CONSTRAINT fk_post_source_occurrence_source FOREIGN KEY (source_blog_id) REFERENCES source_blog (id),
  CONSTRAINT uk_post_source_occurrence_source_url UNIQUE (source_blog_id, origin_url)
);

CREATE INDEX idx_post_source_occurrence_archived_post_id ON post_source_occurrence (archived_post_id);

CREATE TABLE ai_summary (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  archived_post_id BIGINT NOT NULL,
  version_no INTEGER NOT NULL,
  summary_state VARCHAR(30) NOT NULL,
  headline VARCHAR(500),
  bullets_json TEXT,
  model_name VARCHAR(100),
  prompt_version VARCHAR(100),
  generated_at TIMESTAMP WITH TIME ZONE,
  is_current BOOLEAN NOT NULL,
  failure_reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_ai_summary_post FOREIGN KEY (archived_post_id) REFERENCES archived_post (id),
  CONSTRAINT uk_ai_summary_post_version UNIQUE (archived_post_id, version_no)
);

CREATE INDEX idx_ai_summary_current ON ai_summary (archived_post_id, is_current);

CREATE TABLE collection_run (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_blog_id BIGINT NOT NULL,
  started_at TIMESTAMP WITH TIME ZONE NOT NULL,
  finished_at TIMESTAMP WITH TIME ZONE,
  status VARCHAR(30) NOT NULL,
  collected_count INTEGER NOT NULL,
  new_post_count INTEGER NOT NULL,
  failure_reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_collection_run_source_blog FOREIGN KEY (source_blog_id) REFERENCES source_blog (id)
);

CREATE INDEX idx_collection_run_source_blog_id ON collection_run (source_blog_id);
CREATE INDEX idx_collection_run_status ON collection_run (status);

CREATE TABLE subscriber (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(320) NOT NULL,
  status VARCHAR(40) NOT NULL,
  manage_token_hash VARCHAR(128),
  verified_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_subscriber_email UNIQUE (email),
  CONSTRAINT uk_subscriber_manage_token_hash UNIQUE (manage_token_hash)
);

CREATE TABLE subscription_verification_request (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscriber_id BIGINT NOT NULL,
  token_hash VARCHAR(128) NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  used_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_subscription_verification_subscriber FOREIGN KEY (subscriber_id) REFERENCES subscriber (id),
  CONSTRAINT uk_subscription_verification_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_subscription_verification_subscriber_id ON subscription_verification_request (subscriber_id);

CREATE TABLE company_subscription (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscriber_id BIGINT NOT NULL,
  company_id BIGINT NOT NULL,
  active BOOLEAN NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_company_subscription_subscriber FOREIGN KEY (subscriber_id) REFERENCES subscriber (id),
  CONSTRAINT fk_company_subscription_company FOREIGN KEY (company_id) REFERENCES company (id),
  CONSTRAINT uk_company_subscription_subscriber_company UNIQUE (subscriber_id, company_id)
);

CREATE INDEX idx_company_subscription_company_active ON company_subscription (company_id, active);

CREATE TABLE notification_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subscriber_id BIGINT NOT NULL,
  archived_post_id BIGINT NOT NULL,
  channel VARCHAR(30) NOT NULL,
  status VARCHAR(30) NOT NULL,
  requested_at TIMESTAMP WITH TIME ZONE NOT NULL,
  sent_at TIMESTAMP WITH TIME ZONE,
  failure_reason TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_notification_event_subscriber FOREIGN KEY (subscriber_id) REFERENCES subscriber (id),
  CONSTRAINT fk_notification_event_post FOREIGN KEY (archived_post_id) REFERENCES archived_post (id),
  CONSTRAINT uk_notification_event_subscriber_post UNIQUE (subscriber_id, archived_post_id)
);

CREATE INDEX idx_notification_event_status_requested ON notification_event (status, requested_at);

CREATE TABLE admin_user (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(320) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(30) NOT NULL,
  active BOOLEAN NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT uk_admin_user_email UNIQUE (email)
);

CREATE TABLE admin_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_user_id BIGINT,
  action_type VARCHAR(100) NOT NULL,
  target_type VARCHAR(100) NOT NULL,
  target_id BIGINT NOT NULL,
  before_json TEXT,
  after_json TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_admin_audit_log_admin_user FOREIGN KEY (admin_user_id) REFERENCES admin_user (id)
);

CREATE INDEX idx_admin_audit_log_admin_user_id ON admin_audit_log (admin_user_id);
CREATE INDEX idx_admin_audit_log_target_created ON admin_audit_log (target_type, target_id, created_at);
