CREATE TABLE feed_entry_snapshot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  archived_post_id BIGINT NOT NULL,
  source_blog_id BIGINT NOT NULL,
  collection_run_id BIGINT NOT NULL,
  title VARCHAR(500) NOT NULL,
  origin_url VARCHAR(1000) NOT NULL,
  canonical_url VARCHAR(1000) NOT NULL,
  canonical_fingerprint VARCHAR(128) NOT NULL,
  published_at TIMESTAMP WITH TIME ZONE NOT NULL,
  collected_at TIMESTAMP WITH TIME ZONE NOT NULL,
  summary_text TEXT,
  duplicate_type VARCHAR(30) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fk_feed_entry_snapshot_post FOREIGN KEY (archived_post_id) REFERENCES archived_post (id),
  CONSTRAINT fk_feed_entry_snapshot_source FOREIGN KEY (source_blog_id) REFERENCES source_blog (id),
  CONSTRAINT fk_feed_entry_snapshot_collection_run FOREIGN KEY (collection_run_id) REFERENCES collection_run (id),
  CONSTRAINT uk_feed_entry_snapshot_source_url UNIQUE (source_blog_id, origin_url)
);

CREATE INDEX idx_feed_entry_snapshot_archived_post_id ON feed_entry_snapshot (archived_post_id);
CREATE INDEX idx_feed_entry_snapshot_collection_run_id ON feed_entry_snapshot (collection_run_id);
CREATE INDEX idx_feed_entry_snapshot_fingerprint ON feed_entry_snapshot (canonical_fingerprint);
